/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import java.util.Random;
import static proyecto_final.PanelMostrar.preguntas;

/**
 *
 * @author bautista
 */
public class D7 extends javax.swing.JFrame {
    private String nombre;
    private String materia;
    private String matricula;
    private String tipoExamen;
    private String carrera;
    private Integer pregExamen;
    private Integer semestre;
    private String[] preguntas;
    private Integer[] rand;
    private String[][] arr;
    private Integer[] boton;
    private Integer[] boton1;
    private Integer[] indices;
    private String[] contestar;
    private Integer aciertos;
    private String[][] arr1;
    
    private PanelMostrar pm1;
    /**
     * Creates new form D7
     */
    public D7() {
        preguntas=new String[PanelMostrar.n];
        arr=new String[PanelMostrar.n][4];
        rand=new Integer[PanelMostrar.n2];
        boton=new Integer[PanelMostrar.n];
        pregExamen=rand.length;
        boton1=new Integer[rand.length];
        indices=new Integer[boton.length];
        aciertos=0;
        for (int i = 0; i < boton1.length; i++) {
            boton1[i]=5;
        }
        arr1=new String[rand.length][4];
        contestar=new String[rand.length];
        Random random=new Random();
        for (int i = 0; i < PanelMostrar.n; i++) {
            preguntas[i]=PanelMostrar.preguntas[i];
        }
       for(int i=0; i<4; i++){
	for(int j=0; j<PanelMostrar.n; j++){
            arr[j][i]=HacerPreguntas.preg[j];     
	}
	}
        //Ley de Ampere -Ley de Lenz - Ley de Faraday -Ley de Gauss.
        
        for (int i = 0; i < rand.length; i++) {
            rand[i]=random.nextInt((PanelMostrar.n)-1)+1;
//            System.out.print(rand[i]+" ");
            if(i>0){
            for (int j = i-1; -1 < j; j--) {
                if(rand[i]==rand[j]){
                    do{
                    rand[i]=random.nextInt((PanelMostrar.n)-1)+1;
                    }while(rand[i]==rand[j]);
                }
            }
            }
            contestar[i]=preguntas[rand[i]];
            arr1[i][0]=arr[rand[i]][0];
            arr1[i][1]=arr[rand[i]][1];
            arr1[i][2]=arr[rand[i]][2];
            arr1[i][3]=arr[rand[i]][3];
            indices[i]=boton[rand[i]];
        }
    
        initComponents();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonver = new javax.swing.JButton();
        jButtonatras = new javax.swing.JButton();
        alumno = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        carreraT = new javax.swing.JTextField();
        semestreT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CARRERA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("SEMESTRE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ALUMNO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("USUARIO");

        jButtonver.setText("Ver Examenes");
        jButtonver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverActionPerformed(evt);
            }
        });

        jButtonatras.setText("Atrás");

        alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnoMouseClicked(evt);
            }
        });

        carreraT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        carreraT.setText("CARRERA");
        carreraT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carreraTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumno)
                    .addComponent(usuario)
                    .addComponent(carreraT, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(semestreT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonatras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonver)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(carreraT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addComponent(semestreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonatras)
                    .addComponent(jButtonver))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoMouseClicked

    private void carreraTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carreraTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_carreraTMouseClicked

    private void jButtonverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverActionPerformed
       
        System.out.println(PanelMostrar.n);
        for (int i = 0; i < PanelMostrar.n; i++) {
           
            System.out.println(PanelMostrar.preguntas[i]);
            System.out.println(HacerPreguntas.preg[i]);
           
        }
        ResponderExamen ventana = new ResponderExamen();
        ventana.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D7().setVisible(true);
            }
        });
    }
    public void mostrarPreguntasyRespuestas(){
        for (int i = 0; i < contestar.length; i++) {
            System.out.println((i+1)+"."+contestar[i]);
            System.out.println(arr1[i][0]);
            System.out.println(arr1[i][1]);
            System.out.println(arr1[i][2]);
            System.out.println(arr1[i][3]);
            System.out.println(indices[i]);
        }
    }
    
    public String getPregunta(Integer n){
        return contestar[n];
    }
    public String getRespuesta(Integer n,Integer i){
        return arr1[n][i];
    }
    public String mostrarContestar(Integer i){
            if(boton1[i]==indices[i]){
                aciertos++;
                return ((i+1)+". "+contestar[i]+" CORRECTO\n  Tu respuesta: "+arr1[i][boton1[i]-1]+"\n  Respuesta correcta: "+arr1[i][indices[i]-1]);
                
            }else{
                return ((i+1)+". "+contestar[i]+" INCORRECTA\n  Tu respuesta: "+arr1[i][boton1[i]-1]+"\n  Respuesta correcta: "+arr1[i][indices[i]-1]);
            }
    }
    public Integer getAciertos(){
        return aciertos;
    }
    public void mostrarNumeros(){
        System.out.println("");
        for (int i = 0; i < rand.length; i++) {
            System.out.print(rand[i]+" ");
            System.out.println(contestar[i]);
        }
    }
    

    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    

    public void setNombre(String nmb){
        nombre=nmb;
    }
    public String getNombre(){
        return nombre;
    }
    public String getMateria() {
        return materia;
    }

    public String getTipoExamen() {
        return tipoExamen;
    }

    public String getCarrera() {
        return carrera;
    }

    public Integer getPregExamen() {
        return pregExamen;
    }

    public Integer getSemestre() {
        return semestre;
    }

    public String[] getPreguntas() {
        return preguntas;
    }

    public String[][] getArr() {
        return arr;
    }
    
     public void setBoton1(Integer btn, Integer op) {
        boton1[btn]=op;
    }
    public Integer getBoton1(Integer c) {
        return boton1[c];
    }

    public void setMateria(String materia) {
        this.materia = materia;
    }

    public void setTipoExamen(String tipoExamen) {
        this.tipoExamen = tipoExamen;
    }

    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }

    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }
    public void setPreguntas(String[] preguntas) {
        this.preguntas = preguntas;
    }

    public void setArr(String[][] arr) {
        this.arr = arr;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alumno;
    private javax.swing.JTextField carreraT;
    private javax.swing.JButton jButtonatras;
    private javax.swing.JButton jButtonver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField semestreT;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
